import { WorkSans } from "./fonts";
import "./ui/globals.css";
import { Providers } from "./providers";
import Nav from "./ui/Navbar/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={WorkSans.className}>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
