import {WorkSans} from "./fonts";
import "./ui/globals.css";
import {Providers} from "./providers";
import Nav from "./ui/Navbar/Nav";
import NextTopLoader from 'nextjs-toploader';
import {SessionProvider} from "next-auth/react";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
    title: "LMS", description: "Generated by create next app",
};

export default async function RootLayout({children, params: {session, ...params}}) {
    return (<html lang='en'>
    <body className={WorkSans.className}>
    <SessionProvider session={session}>
        <Providers>
            <NextTopLoader
                showSpinner={false}
            />
            <Nav/>
            {children}
            <ToastContainer
                position="top-center"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
            />
        </Providers>
    </SessionProvider>
    </body>
    </html>);
}
